### ISSUE TITLE
Passwortsperre nur bei Fallback-Startpunkten?

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-root-protection#1]
Die Passwortsperre läßt sich nur bei Startpunkten, die den Sprachenfallback gesetzt haben, einrichten. In den anderen Startpunkten wird die Einstellung nicht angezeigt.
Dabei findet dann aber auch keine Sperre statt, also keine Vererbung der Einstellung aus der Fallback-Sprache.

Die Verkopplung der Startpunkte würde auch oft keinen Sinn machen, da gerade die Eine Sprache schon Online ist, die zweite Sprache aber noch in der Übersetzung, daher unfertig und ausgeblendet.

Wenn ich den Fallback wechsele, kann ich auch den anderen Startpunkt mit dem Passwortschutz einrichten. Die Einstellung ist jeweils gültig, auch wenn die Einstellung ausgeblendet ist.
(Leider gehen aber bei den Fallback-Spielereien die Verlinkungen der Seiten kaputt)

**Comment by richardhj** [comment]
Vielen Dank fürs Testen @do-while.

**Comment by aschempp** [comment]
Macht es denn Sinn eine einzelne Sprache mit einem Passwort zu schützen? Sollte dann nicht besser die (Root)-Seite nicht veröffentlicht sein? Das System würde ja sonst Links zu den geschützten Seiten generieren (z.B. über changelanguage).

Ich dachte jetzt eher man sollte nur in der Root-Seite konfigurieren, und dies sollte auch für alle Sprachen gelten?

**Comment by do-while** [comment]
Das gibt für mich schon Sinn, denn oft ist die Übersetzung noch nicht fertig, wenn die Seite Online gehen soll (muss).
Ich würde in dem Fall natürlich das changelanguage-Modul im Seitenlayout deaktivieren.

Das wäre ja auch ohne diese Änderung möglich gewesen, wenn die Sprachen unterschiedliche Domains hätten, dann hätten beide ja auch den Fallback gesetzt.
